/*
    MODELING CATEGORY SCHEMA 
    -- NAME 
    -- PICTURE
    -- QUOTE (FOR BRANDING)
    -- SUBCATEGORY (NOT IN SCHEMA BUT IN BUSSINESS MODEL)
    -- PRODUCTS (NOT IN SCHEMA BUT IN BUSSINESS MODEL)
    -- SOLD 
    -- QUANTITY
*/