/* 
    SUBCATEGORY MODELING 
    -- NAME 
    -- PICTURE
    -- QUOTE (FOR BRANDING)
    -- CATEGORY (NOT IN SCHEMA BUT IN BUSSINESS MODEL)
    -- PRODUCTS (NOT IN SCHEMA BUT IN BUSSINESS MODEL)
    -- SOLD 
    -- QUANTITY
    
*/